# Generated by Django 3.0.4 on 2020-09-09 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryEvent',
            fields=[
                ('title', models.CharField(max_length=30, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='ClassNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Номер класса',
                'verbose_name_plural': 'Номера классов',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('title', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='Название')),
                ('slug', models.SlugField(verbose_name='Ссылка')),
                ('main_image', models.ImageField(blank=True, upload_to='events/%Y/%m/%h/', verbose_name='Заставка')),
                ('content', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент')),
                ('short_description', tinymce.models.HTMLField(blank=True, null=True, verbose_name='Краткое описание')),
                ('data_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('data_event', models.DateTimeField(verbose_name='Дата мероприятия')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активность мероприятия')),
                ('price', models.FloatField(blank=True, default=0, null=True, verbose_name='Цены')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sore.CategoryEvent', verbose_name='Категория')),
                ('classes', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sore.ClassNumber', verbose_name='Принимающие участие классы')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000, verbose_name='Вопрос')),
                ('image', models.ImageField(blank=True, null=True, upload_to='pictures/', verbose_name='Фото')),
                ('count_answers', models.IntegerField(default=1, verbose_name='Количество ответов')),
                ('count_balls', models.IntegerField(default=1, verbose_name='Количество баллов за правильный ответ')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.ClassNumber', verbose_name='Номер класса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone_number', models.CharField(max_length=12, verbose_name='Телефонный номер')),
                ('name_school', models.CharField(max_length=50, verbose_name='Название школы')),
                ('count', models.IntegerField(default=0, verbose_name='Баллов за правильные ответы')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплачена ли олимпида')),
                ('class_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.ClassNumber', verbose_name='Номер класса')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Школьник',
                'verbose_name_plural': 'Школьники',
            },
        ),
        migrations.CreateModel(
            name='UserInEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paid', models.BooleanField(default=False, verbose_name='Оплатил ли пользователь участие')),
                ('active', models.BooleanField(default=True, verbose_name='Будет ли принимать участие пользователь')),
                ('date_registration', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации на мероприятие')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Student', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Пользователь, принимающий участие в мероприятии',
                'verbose_name_plural': 'Пользователи, принимающие участие в мероприятиях',
            },
        ),
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Question', verbose_name='Вопрос')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Student', verbose_name='Школьник')),
            ],
            options={
                'verbose_name': 'Ответ пользователя',
                'verbose_name_plural': 'Ответы пользователей',
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=1000, verbose_name='Ответ')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Event', verbose_name='Олимпиада')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Question', verbose_name='Вопрос')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
            },
        ),
    ]
