# Generated by Django 3.0.4 on 2020-03-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
        migrations.AlterModelOptions(
            name='classnumber',
            options={'verbose_name': 'Номер класса', 'verbose_name_plural': 'Номера классов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'Школьник', 'verbose_name_plural': 'Школьники'},
        ),
        migrations.AlterModelOptions(
            name='useranswer',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы пользователей'},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together=set(),
        ),
    ]
