# Generated by Django 3.0.4 on 2020-09-09 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='class_number',
        ),
        migrations.AddField(
            model_name='question',
            name='event',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='sore.Event', verbose_name='Олимпиада'),
            preserve_default=False,
        ),
    ]
