# Generated by Django 3.0.4 on 2020-03-31 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sore', '0002_auto_20200331_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Верный ли ответ'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=1000, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='classnumber',
            name='name',
            field=models.CharField(max_length=1, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.ClassNumber', verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=1000, verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='student',
            name='class_number',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.ClassNumber', verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name_school',
            field=models.CharField(max_length=50, verbose_name='Название школы'),
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone_number',
            field=models.CharField(max_length=11, verbose_name='Телефонный номер'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Answer', verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sore.Student', verbose_name='Школьник'),
        ),
    ]
