# Generated by Django 3.0.4 on 2020-04-01 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0003_auto_20200331_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
