# Generated by Django 3.0.4 on 2020-04-01 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0004_question_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='pictures/'),
        ),
    ]
