# Generated by Django 2.2 on 2020-09-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0004_startolymp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='startolymp',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время '),
        ),
        migrations.AlterField(
            model_name='startolymp',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Время '),
        ),
    ]
