# Generated by Django 3.0.4 on 2020-04-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0005_auto_20200401_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
