# Generated by Django 2.2 on 2020-09-11 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0005_auto_20200911_0650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classnumber',
            name='name',
            field=models.CharField(max_length=2, verbose_name='Номер класса'),
        ),
        migrations.AlterField(
            model_name='startolymp',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
