# Generated by Django 2.2 on 2020-09-13 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0006_auto_20200911_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='paid',
        ),
    ]
