# Generated by Django 3.0.4 on 2020-04-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0006_student_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='count',
            field=models.IntegerField(default=0, verbose_name='Баллов за правильные ответы'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='answer',
            field=models.CharField(max_length=1000, verbose_name='Ответ'),
        ),
    ]
