# Generated by Django 2.2 on 2020-09-13 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0007_remove_student_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswer',
            name='correct',
            field=models.BooleanField(default=False, verbose_name='Верный ли ответ'),
        ),
    ]
