# Generated by Django 3.0.4 on 2020-04-01 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0007_auto_20200401_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=0),
        ),
    ]
