# Generated by Django 3.0.4 on 2020-04-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0008_student_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='two_more',
            field=models.BooleanField(default=0),
        ),
    ]
