# Generated by Django 2.2 on 2020-09-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0008_useranswer_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=0, verbose_name='Количество ответов'),
        ),
        migrations.AlterField(
            model_name='startolymp',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время окончания олимпиады пользователем'),
        ),
        migrations.AlterField(
            model_name='startolymp',
            name='start_time',
            field=models.DateTimeField(null=True, verbose_name='Время начала олимпиады пользователем'),
        ),
    ]
