# Generated by Django 3.0.4 on 2020-04-02 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0010_auto_20200402_0129'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='paid',
            field=models.BooleanField(default=0, verbose_name='Оплачена ли олимпида'),
        ),
    ]
