# Generated by Django 3.0.4 on 2020-04-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0011_auto_20200402_0133'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='two_more',
        ),
        migrations.AlterField(
            model_name='student',
            name='telephone_number',
            field=models.CharField(max_length=12, verbose_name='Телефонный номер'),
        ),
    ]
