# Generated by Django 2.2 on 2020-09-08 03:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0013_categoryevent_event_userinevent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='correct',
        ),
        migrations.AddField(
            model_name='answer',
            name='event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='sore.Event', verbose_name='Олимпиада'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='count_answers',
            field=models.IntegerField(default=1, verbose_name='Количество ответов'),
        ),
        migrations.AddField(
            model_name='question',
            name='count_balls',
            field=models.IntegerField(default=1, verbose_name='Количество баллов за правильный ответ'),
        ),
    ]
