# Generated by Django 2.2 on 2020-09-08 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sore', '0014_auto_20200908_0313'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='classes',
            field=models.ManyToManyField(to='sore.ClassNumber', verbose_name='Принимающие участие классы'),
        ),
    ]
